yarnPath: .yarn/releases/yarn-3.2.4.cjs
nodeLinker: "pnp"

# dependency 확장 모듈 설치
packageExtensions:
  'styled-components@*':
    dependencies:
      react-is: '^16.8.0'
  'eslint-plugin-prettier@*':
    dependencies:
      prettier: '^2.0.0'