nodeLinker: pnp

packageExtensions:
  eslint-plugin-prettier@*:
    dependencies:
      prettier: ^2.0.0
  styled-components@*:
    dependencies:
      react-is: ^16.8.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
