import dotenv from "dotenv";
dotenv.config();

export const {
  ACCESS_TOKEN_SECRETKEY,
  REFRESH_TOKEN_SECRETKEY,
  ALGORITHM,
  ACCESS_TOKEN_EXPIRESIN,
  REFRESH_TOKEN_EXPIRESIN,
  ISSUER,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT,
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PWD,
  DB_NAME,
} = process.env;
